config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :booths, param: :uid do
    resources :items
  end

  resources :categories

  get '/nearby_booths', to: "booths#nearby_booths", as: :nearby_booths
  get '/dashboard',     to: "users#dashboard",      as: :dashboard
  get '/items/search',  to: "items#search",         as: :items_search
  post 'contact',       to: 'messages#create'
  root "booths#index"
end

app/models/booth.rb
class Booth < ActiveRecord::Base
  include SharedMethods
  belongs_to :user
  has_many :items
  has_many :images, as: :imageable
  validates :name, :email, :address1, :city, :state, :zipcode, :start_date, :stop_date, presence: true
  before_create :set_uid

  geocoded_by :full_address
  after_validation :geocode

  default_scope { where(archived: false) }

  def other_items(booth, item)
    if booth.items.includes(:images).last(5).include?(item)
      booth.items.includes(:images).last(6) - [item]
    else
      booth.items.includes(:images).last(5)
    end
  end

  def full_address
    [address1, address2, city, state, zipcode].join(', ')
  end

  def set_uid
    self.uid = rand(100000..999999)
  end
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :is_booth_owner?, only: %i[edit update]

  def index
    # visitor_latitude = request.location.latitude
    # visitor_longitude = request.location.longitude
    visitor_latitude = 44.9778
    visitor_longitude = -93.2650
    @booths = Booth.near([visitor_latitude, visitor_longitude], 20).includes(:images)
  end

  def nearby_booths
    # visitor_latitude = request.location.latitude
    # visitor_longitude = request.location.longitude
    visitor_latitude = 44.9778
    visitor_longitude = -93.2650
    render json: Booth.near([visitor_latitude, visitor_longitude], 20).includes(:images).as_json(only: [:uid,
                                                                                                        :name,
                                                                                                        :address1,
                                                                                                        :address2,
                                                                                                        :city,
                                                                                                        :state,
                                                                                                        :zipcode,
                                                                                                        :description,
                                                                                                        :start_date,
                                                                                                        :stop_date,
                                                                                                        :latitude,
                                                                                                        :longitude])
  end

  def new
    @booth = Booth.new
  end

  def create
    @booth = current_user.booths.build(booth_params)
    build_image

    if @booth.save
      redirect_to booth_path(@booth.uid)
    else
      flash[:alert] = @booth.errors.full_messages
      render :new
    end
  end

  def show
    @booth = find_booth
    @items = @booth.items.includes(:images)
  end

  def edit
    @booth = find_booth
    @image = @booth.images.first
  end

  def update
    @booth = find_booth
    if @booth.update(booth_params)
      build_image
      redirect_to booth_path(@booth.uid)
    else
      render :edit
    end
  end

  def destroy
    @booth = find_booth
    @booth.archive
    redirect_to dashboard_path
  end

  private

    def booth_params
      params.require(:booth).permit(:name, :email, :address1, :address2, :city, :state, :zipcode, :start_date, :stop_date)
    end

    def find_booth
      Booth.find_by(uid: params[:uid])
    end

    def is_booth_owner?
      @booth = find_booth
      if @booth.user != current_user
        redirect_to root_path
        flash[:alert] = "You are not authorized to view this booth."
      end
    end

    def build_image
      if params[:booth][:image].present?
        @booth.images.build(image: params[:booth][:image][:image])
      end
    end
end

app/views/booths/_image_or_default.html.erb
<% if booth.images.present? %>
  <%= link_to image_tag(booth.images.first.image.thumb("#{thumb}#").url), booth_path(booth.uid) %>
<% else %>
  <%= link_to image_tag("http://placehold.it/#{thumb}"), booth_path(booth.uid) %>
<% end %>

app/views/booths/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Edit <%= @booth.name %> Booth</h1>
  </div>
</div>

<%= form_for(@booth, url: booth_path(@booth.uid)) do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :address1 %>
      <%= f.text_field :address1 %>
    </div>
    <div class="large-4 columns end">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="large-2 columns">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>
    <div class="large-2 columns end">
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
    </div>
  </div>

  <div class="row">
    <div class="large-6 columns">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="large-6 columns end">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :start_date %>
      <%= f.text_field :start_date, id: "start-date", data: {"date-format" => "yyyy/mm/dd"} %>
    </div>
    <div class="large-4 columns end">
      <%= f.label :stop_date %>
      <%= f.text_field :stop_date, id: "stop-date", data: {"date-format" => "yyyy/mm/dd"} %>
    </div>
  </div>

  <%= f.fields_for :image do |image_field| %>
    <div class="row">
      <div class="large-6 columns">
        <%= image_field.label :image, "Edit Image" %>
        <%= image_field.file_field :image %>
      </div>
    </div>
  <% end %>

  <% if @booth.images.present? %>
    <div class="row">
      <div class="large-6 columns">
        <% @booth.images.each do |image| %>
          <%= image_tag(image.image.thumb("100x100#").url) %>
        <% end %>
      </div>
    </div>
  <% end %>

  <br />

  <div class="row">
    <div class="large-1 columns">
      <%= f.submit "Edit Booth", class: "button primary" %>
    </div>
  </div>
<% end %>

app/views/booths/index.html.erb
<div class="panel custom-panel">
  <div id="wrapper">
    <div id="map" class="clearfix">
    </div>
    <div id="over_map" class="right">
      <%= form_tag items_search_path, method: :get do |f| %>
        <div class="row">
          <div class="large-12 columns">
            <%= label_tag "Search" %>
            <%= text_field_tag :search, nil, autofocus: true, placeholder: "appliances, clothes, etc.", size: 30 %>
          </div>
        </div>

        <div class="row">
          <div class="large-12 columns">
            <%= label_tag "Location" %>
            <%= text_field_tag :location, nil, placeholder: "denver, miami, etc." %>
          </div>
        </div>

        <div class="row">
          <div class="large-12 columns">
            <%= label_tag "Category" %>
            <%= select_tag :category, options_for_select(Category.all.map{ |f| [f.name, f.id] }) %>
          </div>
        </div>
        
        <div class="row">
          <div class="large-12 columns">
            <%= submit_tag 'Search', class: "button success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="reasons full-width">
  <div class="row">
    <div class="text-center reason-title">
      <h2>Start selling today!</h2>
    </div>
    <div class="large-4 columns text-center">
      <i class="fa fa-search"></i>
      <p>Find a garage sale near you.</p>
    </div>
    <div class="large-4 columns text-center">
      <i class="fa fa-archive"></i>
      <p>Start your own garage sale.</p>
    </div>
    <div class="large-4 columns text-center">
      <i class="fa fa-money"></i>
      <p>Earn extra cash...or save some!</p>
    </div>
  </div>
</div>
<div class="featured-section full-width">
<div class="row">
  <div class="small-12 large-12 columns">
    <h2 class="text-center featured">Featured Booths</h2>
  </div>
  <div class="small-12 large-12 columns">
    <div class="items">
      <% @booths.each do |booth| %>
        <div class="large-3 small-6 columns">
          <%= render partial: "booths/image_or_default", locals: { booth: booth, thumb: "500x500"} %>
          <div class="panel">
            <p><%= link_to booth.name, booth_path(booth.uid) %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/booths/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Create a Booth</h1>
  </div>
</div>

<%= form_for @booth do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :address1 %>
      <%= f.text_field :address1 %>
    </div>
    <div class="large-4 columns end">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="large-2 columns">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>
    <div class="large-2 columns end">
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
    </div>
  </div>

  <div class="row">
    <div class="large-6 columns">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="large-6 columns end">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :start_date %>
      <%= f.text_field :start_date, id: "start-date", data: {"date-format" => "yyyy/mm/dd"} %>
    </div>
    <div class="large-4 columns end">
      <%= f.label :stop_date %>
      <%= f.text_field :stop_date, id: "stop-date", data: {"date-format" => "yyyy/mm/dd"} %>
    </div>
  </div>

  <%= f.fields_for :image do |image_field| %>
    <div class="row">
      <div class="large-6 columns">
        <%= image_field.label :image %>
        <%= image_field.file_field :image %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="large-1 columns">
      <%= f.submit "Create Booth", class: "button primary" %>
    </div>
  </div>
<% end %>

app/views/booths/show.html.erb
<div class="row">
  <div class="large-12 columns">

    <div class="row">
      <div class="large-12 columns">
        <div class="row booth-top">

          <div class="large-3 small-12 columns">
            <%= render partial: "booths/image_or_default", locals: { booth: @booth, thumb: "540x500#" } %>
            <div class="hide-for-small panel">
              <h3><%= @booth.name %></h3>
              <h5 class="subheader"><%= @booth.description %></h5>
            </div>
              <a href="#"><div class="panel callout radius"><h6><%= @items.count %> items in your cart</h6></div></a>
          </div>
          
          <div class="large-9 columns">
            <% if current_user == @booth.user %>
              <%= link_to "+ Add Item", new_booth_item_path(@booth.uid), class: "small button" %>
            <% end %>
            <a href="#" class="small secondary radius button split right">Sort <span data-dropdown="item-sort"></span></a>
            <ul id="item-sort" class="f-dropdown open f-open-dropdown" data-dropdown-content="" aria-hidden="false">
              <li><a href="#">By Lowest Price</a></li>
              <li><a href="#">By Highest Price</a></li>
              <li><a href="#">By Category</a></li>
            </ul>
          </div>

          <div class="large-9 columns">
            <div class="row">
              <% @items.each do |item| %>
                <div class="large-3 small-6 columns end">
                  <%= render partial: "items/image_or_default", locals: { item: item, thumb: "200x200#" } %>
                  <div class="panel">
                    <%= link_to truncate(item.name, length: 20), booth_item_path(item.booth.uid, item) %>
                    <h6 class="subheader"><%= number_to_currency(item.price) %></h6>
                  </div>
                </div>
              <% end %>
            </div>
            <ul class="pagination right">
              <li class="arrow unavailable"><a href="">&laquo;</a></li>
              <li class="current"><a href="">1</a></li>
              <li><a href="">2</a></li>
              <li><a href="">3</a></li>
              <li><a href="">4</a></li>
              <li class="unavailable"><a href="">&hellip;</a></li>
              <li><a href="">12</a></li>
              <li><a href="">13</a></li>
              <li class="arrow"><a href="">&raquo;</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>