config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :booths, param: :uid do
    resources :items
  end

  resources :categories

  get '/nearby_booths', to: "booths#nearby_booths", as: :nearby_booths
  get '/dashboard',     to: "users#dashboard",      as: :dashboard
  get '/items/search',  to: "items#search",         as: :items_search
  post 'contact',       to: 'messages#create'
  root "booths#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :booths
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserHelper
  
  def dashboard
    @booths = Booth.where(user_id: current_user)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= current_user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/dashboard.html.erb
<div class="row">
  <h1 class="text-center">My Dashboard</h1>
  <ul class="tabs" data-tab data-options="deep_linking: true; scroll_to_content: false">
    <li class="tab-title active"><a href="#user-info">User Info</a></li>
    <li class="tab-title"><a href="#your-booths">Your Booths</a></li>
  </ul>
  <div class="tabs-content">
    <hr>
    <div class="content active" id="user-info">
      <%= render partial: "devise/user_info" %>
    </div>
    <div class="content" id="your-booths">
      <%= link_to "<i class='fa fa-plus'></i> Add a Booth".html_safe, new_booth_path, class: "tiny button success round" %>
      <table>
        <thead>
          <tr>
            <th width="200">Booth</th>
            <th>Address</th>
            <th width="150"></th>
          </tr>
        </thead>
        <tbody>
          <% @booths.each do |booth| %>
            <tr>
              <td><%= link_to booth.name, booth_path(booth.uid) %></td>
              <td><%= booth.address1 %></td>
              <td>
                <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_booth_path(booth.uid), title: "Edit Booth" %>
                <%= link_to "<i class='fa fa-shopping-basket'></i>".html_safe, booth_items_path(booth.uid), title: "Items" %>
                <%= link_to "<i class='fa fa-trash'></i>".html_safe, booth_path(booth.uid), method: :delete, data: {confirm: "Are you sure?"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>