config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :booths, param: :uid do
    resources :items
  end

  resources :categories

  get '/nearby_booths', to: "booths#nearby_booths", as: :nearby_booths
  get '/dashboard',     to: "users#dashboard",      as: :dashboard
  get '/items/search',  to: "items#search",         as: :items_search
  post 'contact',       to: 'messages#create'
  root "booths#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  include SharedMethods
  belongs_to :booth
  belongs_to :category
  has_many :images, as: :imageable
  validates :name, :description, :price, presence: true

  default_scope { where(archived: false) }

  def self.search(params)
    # Need to get items based on booth location.
    # Get nearby booths, get all their items, then search
    # those items. ".map" returns array and we need
    # ActiveRecord Relation.
    booths = params[:location].present? ? Booth.near(params[:location], 20) : Booth.all
    items = get_booths_items(booths, params)
    items = Item.where(id: items)
    items = items.where("name ilike ?", "%#{params[:search]}%") if params[:search].present?
    items
  end

  def self.get_booths_items(booths, params)
    items = []
    booths.each { |booth| items << booth.items }
    items = items.map { |item| item.where(category_id: params[:category].to_i) }.flatten
    items = items.map { |item| item.id }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :belongs_to_user?, only: %i[edit update]

  def index
    @booth = find_booth
    @items = @booth.items
  end

  def new
    @booth = find_booth
    @item = Item.new(booth: @booth)
  end

  def create
    @booth = find_booth
    @item = @booth.items.build(item_params)
    build_image

    respond_to do |format|
      if @item.save
        format.html { redirect_to booth_items_path(@booth.uid, @item), notice: "Item created successfully."}
        format.json { render :show, status: :created, location: @item }
      else
        format.html { 
          flash[:danger] = @item.errors.full_messages.to_sentence
          render :new
        }
        format.json { render json: @item.errors, status: :unprocessible_entity }
      end
    end
  end

  def show
    @booth = find_booth
    @item = @booth.items.find(params[:id])
  end

  def edit
    @booth = find_booth
    @item = find_item
  end

  def update
    @booth = find_booth
    @item = find_item
    @item.update(item_params)
    @item.images.create(image: params[:item][:image][:image]) if params[:item][:image].present?
    redirect_to booth_item_path(@booth.uid, @item)
  end

  def destroy
    @booth = find_booth
    @item = find_item
    @item.archive
    redirect_to booth_items_path(@booth.uid)
  end

  def search
    if params.present?
      @items = Item.includes(:images).includes(:booth).search(params)
    else
      @items = Item.all
    end
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :price, :category_id)
    end

    def find_booth
      Booth.find_by(uid: params[:booth_uid])
    end

    def find_item
      Item.find(params[:id])
    end

    def build_image
      if params[:item][:image].present?
        @item.images.build(image: params[:item][:image][:image])
      end
    end

    def belongs_to_user?
      if current_user != Item.find(params[:id]).booth.user
        flash[:alert] = "You are not the owner of this item!"
        redirect_to root_path
      end
    end

end

app/views/items/_image_or_default.html.erb
<% if item.images.present? %>
  <%= link_to image_tag(item.images.first.image.thumb("#{thumb}").url), booth_item_path(@booth.uid, item) %>
<% else %>
  <%= link_to image_tag("http://placehold.it/#{thumb}"), booth_item_path(@booth.uid, item) %>
<% end %>

app/views/items/_item_image.html.erb
<% if @item.images.present? %>

  <% @item.images.each do |image| %>
    <div data-thumb=<%= image.image.thumb("#{thumb}").url %>>
      <%= image_tag(image.image.thumb("#{thumb}").url) %>
    </div>
  <% end %>

<% else %>

  <div data-thumb="http://placehold.it/540x400">
    <%= image_tag("http://placehold.it/540x400") %>
  </div>

<% end %>

app/views/items/_search_items_images.html.erb
<% if item.images.present? %>
  <%= link_to image_tag(item.images.first.image.thumb("100x100#").url, { align: "left", style: "margin-right: 2em;" }), booth_item_path(item.booth.uid, item) %>
<% else %>
  <%= link_to image_tag("http://placehold.it/100x100", { align: "left", style: "margin-right: 2em;" }), booth_item_path(item.booth.uid, item) %>
<% end %>

app/views/items/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Edit <%= @item.name %> Item</h1>
  </div>
</div>

<%= form_for([@booth, @item], url: booth_item_path(@booth.uid, @item)) do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :category_id, "Category" %>
      <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <%= f.fields_for :image do |image_field| %>
    <div class="row">
      <div class="large-6 columns">
        <%= image_field.label :image, "Add More Images" %>
        <%= image_field.file_field :image %>
      </div>
    </div>
  <% end %>

  <% if @item.images.present? %>
    <div class="row">
      <div class="large-6 columns">
        <% @item.images.each do |image| %>
          <%= image_tag(image.image.url) %>
        <% end %>
      </div>
    </div>
  <% end %>

  <br />

  <div class="row">
    <div class="large-1 columns">
      <%= f.submit "Edit Item", class: "button primary" %>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2><%= link_to @booth.name, booth_path(@booth.uid) %> Items</h2>
    <%= link_to "+ Add Item", new_booth_item_path(@booth.uid), class: "small button" %>
    <table>
      <thead>
        <tr>
          <th width="200">Name</th>
          <th>Description</th>
          <th width="150">Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td><%= item.description %></td>
            <td><%= number_to_currency(item.price) %></td>
            <td>
              <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_booth_item_path(@booth.uid, item), title: "Edit Item" %>
              <%= link_to "<i class='fa fa-trash'></i>".html_safe, booth_item_path(@booth.uid, item), method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Create an Item</h1>
  </div>
</div>

<%= form_for([@booth, @item], url: booth_items_path(@booth.uid, @item)) do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :category_id, "Category" %>
      <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <%= f.fields_for :image do |image_field| %>
    <div class="row">
      <div class="large-6 columns">
        <%= image_field.label :image %>
        <%= image_field.file_field :image %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="large-1 columns">
      <%= f.submit "Add Item", class: "button primary" %>
    </div>
  </div>
<% end %>

app/views/items/search.html.erb
<div class="row">
  <h3>Search Results</h3>
  <hr>
</div>
<div class="row">

  <div class="small-8 large-8 columns">
    <% @items.each do |item| %>
      <div class="row">
        <%= render partial: "items/search_items_images", locals: { item: item } %>
        <p><%= link_to item.name, booth_item_path(item.booth.uid, item) %> - <%= number_to_currency(item.price) %></p>
        <p><%= item.description %></p>
      </div>
      <div class="row">
        <hr>
      </div>
    <% end %>
  </div>

  <div class="small-4 large-4 columns">
    <%= form_tag items_search_path, method: :get do |f| %>
      <div class="row">
        <div class="large-12 columns">
          <%= label_tag "Search" %>
          <%= text_field_tag :search, nil, placeholder: "appliances, clothes, etc.", size: 30 %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <%= label_tag "Location" %>
          <%= text_field_tag :location, nil, placeholder: "denver, miami, etc." %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <%= label_tag "Category" %>
          <%= select_tag :category, options_for_select(Category.all.map{ |f| [f.name, f.id] }) %>
        </div>
      </div>
      
      <div class="row">
        <div class="large-12 columns">
          <%= submit_tag 'Search', class: "button success" %>
        </div>
      </div>
    <% end %>
  </div>

</div>
<div class="row">
  <div class="small-8 large-8 columns right">
    <ul class="pagination">
      <li class="arrow unavailable"><a href="">&laquo;</a></li>
      <li class="current"><a href="">1</a></li>
      <li><a href="">2</a></li>
      <li><a href="">3</a></li>
      <li><a href="">4</a></li>
      <li class="unavailable"><a href="">&hellip;</a></li>
      <li><a href="">12</a></li>
      <li><a href="">13</a></li>
      <li class="arrow"><a href="">&raquo;</a></li>
    </ul>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <h2><%= link_to @item.booth.name, booth_path(@item.booth.uid) %></h2>
  <h3><%= @item.name %> - <%= number_to_currency(@item.price) %></h3>
</div>
<div class="row">
  <hr>
  <div class="large-7 columns">
    <div class="items-show">
      <%= render partial: "items/item_image", locals: { item: @item, thumb: "500x500"} %>
    </div>
  </div>
  <div class="large-5 columns">
    <h4><%= @item.name %></h4>
    <p><%= @item.description %></p>
  </div>
</div>
<div class="row">
  <hr>
  <div class="large-6 columns">
    <h4>Contact Owner</h4>
    <%= form_for Message.new, url: contact_path do |message_form| %>
      <%= message_form.hidden_field :owner_email, value: "#{@item.booth.email}" %>
      <%= message_form.text_field :name, placeholder: "Your Name" %>
      <%= message_form.email_field :email, placeholder: "Your Email"%>
      <%= message_form.text_area :content, placeholder: "I want to know more about #{@item.name}!", rows: "10" %>
      <%= message_form.submit "Send", class: "button" %>
    <% end %>
  </div>
  <div class="large-6 columns">
    <div id="item-map" class="clearfix">
    </div>
  </div>
</div>
<div class="row">
  <hr>
  <div class="large-12 columns">
    <h4>Other items in this booth</h4>
    <% @booth.other_items(@booth, @item).each do |item| %>
      <%= render partial: "items/image_or_default", locals: { item: item, thumb: "190x150" } %>
    <% end %>
  </div>
</div>
<div class="row">
  <hr>
</div>

<script type="text/javascript">
  function itemMap() {
    var mapCanvas = document.getElementById('item-map');
    var mapOptions = {
      center: new google.maps.LatLng(<%= @item.booth.latitude %>, <%= @item.booth.longitude %>),
      zoom: 14,
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    var map = new google.maps.Map(mapCanvas, mapOptions)

    var myLatLng = {lat: <%= @item.booth.latitude %>, lng: <%= @item.booth.longitude %>};
    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'Hello World!'
    });
  }
  google.maps.event.addDomListener(window, 'load', itemMap);
</script>